### ISSUE TITLE
Issue #9

### ISSUE THREAD

**Issue by galund** [petewarden/openheatmap#10]
This is my fix for Issue #9, apologies if something is wrong I never used github before :-)

https://github.com/petewarden/openheatmap/issues/9

**Comment by petewarden** [comment]
Thanks for that, I've merged it in. Funnily enough I noticed something
similar performance-wise when I reused some of the code in another project,
and ported it over to the prototype method, but didn't backport the changes:
https://github.com/petewarden/flxjs/blob/master/flxjs.js

I really appreciate the patch, and great to hear you've been getting use
out of the component!

cheers,
           Pete

On Fri, Feb 3, 2012 at 9:50 AM, galund-mintel <
reply@reply.github.com
