### ISSUE TITLE
Openheatmap on my own server

### ISSUE THREAD

**Issue by idlikej** [petewarden/openheatmap#8]
Hi. I would like to know if can i organize a local service openheatmap on my own server? I want to use it without connection to the Internet. Could you describe the the process of deploying the service, if possible. Thanks. (Sorry for my english)

**Comment by petewarden** [comment]
Here's a guide to the process:
https://github.com/petewarden/openheatmap/wiki/How-to-use-OpenHeatMap-within-your-own-site

Does that help?

On Fri, Dec 16, 2011 at 6:27 AM, m0razzm <
reply@reply.github.com

**Comment by idlikej** [comment]
I used this manual before. Strange, but some csv files do not load the data to the card. Now everything is working. Thanks
